// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHoCp3OEQ4NsA4luBbj4zBCM6SKwFU84',
    appId: '1:227166830823:web:0b1d42987f1e1076d86242',
    messagingSenderId: '227166830823',
    projectId: 'goldventory',
    authDomain: 'goldventory.firebaseapp.com',
    storageBucket: 'goldventory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBroWuIu8Ap9lwjY6BGnV7X4MzBcj0UcTA',
    appId: '1:227166830823:android:1f90dfc69ae1008bd86242',
    messagingSenderId: '227166830823',
    projectId: 'goldventory',
    storageBucket: 'goldventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVocRlNo4L9vT01bmkyV-fQyyxg7tUGY',
    appId: '1:227166830823:ios:8c8c9dbcb1fac42ed86242',
    messagingSenderId: '227166830823',
    projectId: 'goldventory',
    storageBucket: 'goldventory.firebasestorage.app',
    iosBundleId: 'com.darshangold.goldventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVocRlNo4L9vT01bmkyV-fQyyxg7tUGY',
    appId: '1:227166830823:ios:8c8c9dbcb1fac42ed86242',
    messagingSenderId: '227166830823',
    projectId: 'goldventory',
    storageBucket: 'goldventory.firebasestorage.app',
    iosBundleId: 'com.darshangold.goldventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxHoCp3OEQ4NsA4luBbj4zBCM6SKwFU84',
    appId: '1:227166830823:web:b30425723b108a1bd86242',
    messagingSenderId: '227166830823',
    projectId: 'goldventory',
    authDomain: 'goldventory.firebaseapp.com',
    storageBucket: 'goldventory.firebasestorage.app',
  );
}
